name: Keep Project Alive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'   # run daily at noon UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase with anon key
        run: |
          echo "Pinging Supabase..."
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhaHBhYnNxeXl1dmJranlrbG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDA3ODAsImV4cCI6MjA3MzMxNjc4MH0.B49lv7SCMyYy_vkZSFKoGnxRl7gpZDDGGJsKJxZlAZc" \
            https://dahpabsqyyuvbkjyklov.supabase.co/rest/v1/)
          echo "Response code: $response"
          if [ "$response" -eq 200 ]; then
            echo "✅ Supabase is active and responding"
          else
            echo "⚠️ Warning: Supabase returned status $response"
            exit 1
          fi
